"""add enable field to user table

Revision ID: 2d5f574cc368
Revises: b063f71125af
Create Date: 2025-03-13 11:44:01.528271

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2d5f574cc368"
down_revision: Union[str, None] = "b063f71125af"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("enable", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "enable")
    # ### end Alembic commands ###
